{"name": "Проверка получения ошибки при повторном использовании логина для создания курьера", "status": "passed", "description": "Проверяются код и тело ответа.", "start": 1726654849522, "stop": 1726654849789, "uuid": "3461df3a-3166-4ed2-9644-28ebd58bae6e", "historyId": "6f67603245d03577c0bb7ad6998f5f65", "testCaseId": "6f67603245d03577c0bb7ad6998f5f65", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_courier_account_login_taken_conflict", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "minergenon"}, {"name": "thread", "value": "244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}